#!/usr/bin/env python3
#
# media-tools
# Copyright (C) 2017-2021 Olivier Korach
# mailto:olivier.korach AT gmail DOT com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
print('''
Collections of utilities to manipulate media file
See tools built-in -h help and https://github.com/okorach/audio-video-tools for more documentation
Available tools:
- video-encode
- media-specs
- video-speed
- image-poster
- image-blinds
- image-shake
- image-scale
- image-stack
- image-to-video
- video-mux
- video-concat
- media-crop
- media-volume
- video-cut
- video-stabilize
- audio-album-art
- image-to-video
- video-slideshow
- video-reverse
- video-metadata
''')
